name: Sample Jekyll Blog
description: A css.
author: Zana
author_email: you@example.com
category_dir: /
baseurl: foxy
url: https://p2401470.github.io/
markdown: rdiscount
permalink: pretty
# paginate: 3

collections:
  - docs
    output: true

exclude: [
  README.markdown,
  package.json,
  grunt.js,
  Gruntfile.js,
  Gruntfile.coffee,
  node_modules
]
