name: Sample Jekyll Blog
description: This is a sample Jekyll Blog.
author: Your Name
author_email: you@example.com
category_dir: /
baseurl: foxy
url: https://p2401470.github.io/
markdown: rdiscount
permalink: pretty
# paginate: 3

exclude: [
  README.markdown,
  package.json,
  grunt.js,
  Gruntfile.js,
  Gruntfile.coffee,
  node_modules
]
